name: pizzeria_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.1.0

  # Firebase
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  firebase_auth: ^6.1.3
  firebase_messaging: ^16.1.0          # ← Agregado ^
  firebase_app_check: 0.4.1+3
  
  # Maps y Localización
  google_maps_flutter: ^2.14.0
  google_maps_flutter_web: ^0.5.10    # ← NUEVO - Soporte para web
  geolocator: ^14.0.2
  
  # Notificaciones
  flutter_local_notifications: ^18.0.1 # ← Agregado ^
  
  # Otros
  dio: ^5.9.0
  intl: ^0.20.2
  provider: ^6.1.2
  permission_handler: ^12.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

