// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfNBRtaaEsbGYdqG2_WO5xIUsrCW9FXdY',
    appId: '1:407730041770:web:d9842f5093d43a9bc031d3',
    messagingSenderId: '407730041770',
    projectId: 'app-pizzeria-ecuador-2005',
    authDomain: 'app-pizzeria-ecuador-2005.firebaseapp.com',
    storageBucket: 'app-pizzeria-ecuador-2005.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzu_MLybCMiA3bRajrdJ1V3TvAcFYXNjk',
    appId: '1:407730041770:android:4cfaec380587b092c031d3',
    messagingSenderId: '407730041770',
    projectId: 'app-pizzeria-ecuador-2005',
    storageBucket: 'app-pizzeria-ecuador-2005.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnLRmqXicLRNscR6f1Lpn-pTx6cMwMc2w',
    appId: '1:407730041770:ios:f601598ae663eabfc031d3',
    messagingSenderId: '407730041770',
    projectId: 'app-pizzeria-ecuador-2005',
    storageBucket: 'app-pizzeria-ecuador-2005.firebasestorage.app',
    iosBundleId: 'com.example.pizzeriaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnLRmqXicLRNscR6f1Lpn-pTx6cMwMc2w',
    appId: '1:407730041770:ios:f601598ae663eabfc031d3',
    messagingSenderId: '407730041770',
    projectId: 'app-pizzeria-ecuador-2005',
    storageBucket: 'app-pizzeria-ecuador-2005.firebasestorage.app',
    iosBundleId: 'com.example.pizzeriaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfNBRtaaEsbGYdqG2_WO5xIUsrCW9FXdY',
    appId: '1:407730041770:web:c50219cb394d14cac031d3',
    messagingSenderId: '407730041770',
    projectId: 'app-pizzeria-ecuador-2005',
    authDomain: 'app-pizzeria-ecuador-2005.firebaseapp.com',
    storageBucket: 'app-pizzeria-ecuador-2005.firebasestorage.app',
  );
}
